subprojects {
  dependencies {
    implementation project(path: ':', configuration: 'namedElements')
  }

  sourceSets {
    main {
      java {
        srcDirs += file '../src/main/java'
        include '**/version/mixin/*.java'
        include '**/version/*.java'
      }
      resources.srcDirs += file '../src/main/resources'
    }
    test {
      java.srcDirs += file '../src/test/java'
      resources.srcDirs += file '../src/test/resources'
    }
  }
}
