plugins {
  alias libs.plugins.loom apply false
}

allprojects {
  if (project.path.startsWith(':modules') && project.path.count(':') < 3)
    return

  apply plugin: libs.plugins.loom.get().pluginId

  version = mod_version
  group = maven_group
  base.archivesName = "$rootProject.name-$name"

  dependencies {
    minecraft group: 'com.mojang', name: 'minecraft', version: minecraft_version
    println "Minecraft: $minecraft_version"
    mappings loom.layered {
      officialMojangMappings { nameSyntheticMembers = true }
    }
    modImplementation libs.loader

    if (project == rootProject)
      return

    testImplementation libs.junit
    testImplementation libs.loader.junit
    testImplementation libs.mockito
    testImplementation libs.mojang.logging

    if (project.path == ':ap')
      return

    modImplementation fabricApi.module('fabric-resource-loader-v0', fabric_api_version)
    modImplementation fabricApi.module('fabric-key-binding-api-v1', fabric_api_version)
    annotationProcessor implementation(project(path: ':ap', configuration: 'namedElements'))

    if (project.path == ':core')
      return

    implementation project(path: ':core', configuration: 'namedElements')
  }

  java {
    toolchain.languageVersion = JavaLanguageVersion.of java_version
    println "Java: $java_version"
    withSourcesJar()
  }

  processResources {
    def f = file 'gradle.properties'
    if (f.exists())
      inputs.file f
    filesMatching 'fabric.mod.json', {
      expand project.properties
    }
  }

  tasks.withType Jar configureEach {
    from rootProject.file('LICENSE')
  }

  test {
    useJUnitPlatform()
    workingDir = rootProject.layout.buildDirectory.file 'test-run'
    workingDir.mkdir()
  }

  if (project != rootProject)
    rootProject.dependencies {
      include project
    }
}

base.archivesName = mod_id
