import net.ornithemc.ploceus.api.GameSide

plugins {
  alias libs.plugins.loom apply false
  alias libs.plugins.ploceus apply false
}

allprojects {
  if (project.path.startsWith(':modules') && project.path.count(':') < 3)
    return

  apply plugin: libs.plugins.loom.get().pluginId
  apply plugin: libs.plugins.ploceus.get().pluginId

  version = mod_version
  group = maven_group
  base.archivesName = "$rootProject.name-$name"

//  project.ploceus.generation = 2
  switch (project.findProperty('environment')) {
    case 'client':
      loom.clientOnlyMinecraftJar()
      ploceus.clientOnlyMappings()
      ploceus.side = GameSide.CLIENT
  }

  dependencies {
    minecraft group: 'com.mojang', name: 'minecraft', version: minecraft_version
    println "Minecraft: $minecraft_version"
    mappings ploceus.featherMappings(feather_build /*'3'*/)
    if (project.hasProperty 'raven_build')
      exceptions ploceus.raven(raven_build)
    if (project.hasProperty 'sparrow_build')
      signatures ploceus.sparrow(sparrow_build)
    if (project.hasProperty 'nests_build')
      nests ploceus.nests(nests_build)
    modImplementation libs.loader

    if (project == rootProject)
      return

    testImplementation libs.junit
    testImplementation libs.loader.junit
    testImplementation libs.mockito
    testImplementation libs.mojang.logging

    if (project.path == ':ap')
      return

    annotationProcessor implementation(project(path: ':ap', configuration: 'namedElements'))

    if (project.path == ':core')
      return

    implementation project(path: ':core', configuration: 'namedElements')
  }

  java {
    toolchain.languageVersion = JavaLanguageVersion.of 8
    withSourcesJar()
  }

  processResources {
    def f = file 'gradle.properties'
    if (f.exists())
      inputs.file f
    filesMatching 'fabric.mod.json', {
      expand project.properties
    }
  }

  tasks.withType Jar configureEach {
    from rootProject.file('LICENSE')
  }

  test {
    useJUnitPlatform()
    workingDir = rootProject.layout.buildDirectory.file 'test-run'
    workingDir.mkdir()
  }

  if (project != rootProject)
    rootProject.dependencies {
      include project
    }
}

base.archivesName = mod_id
