plugins {
  alias libs.plugins.loom apply false
  alias libs.plugins.ploceus apply false
}

allprojects {
  if (project.path == ':version')
    return

  apply plugin: libs.plugins.loom.get().pluginId
  apply plugin: libs.plugins.ploceus.get().pluginId
  apply plugin: 'idea'

  version = mod_version
  group = maven_group
  base.archivesName = "$rootProject.name-$name"

  //gen2//ploceus.intermediaryGeneration = 2

  dependencies {
    println "Minecraft: $minecraft_version"
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings ploceus.featherMappings(feather_build)

    if (project.hasProperty('sparrow_build'))
      signatures ploceus.sparrow(sparrow_build)

    modImplementation libs.loader

    ploceus.dependOsl libs.versions.osl.get()

    testImplementation libs.junit
    testImplementation libs.loader.junit
    testImplementation libs.mockito
    testImplementation libs.mojang.logging
  }

  loom {
    log4jConfigs.from project.rootProject.file('src/test/resources/log4j.xml')
    runs {
      client.ideConfigGenerated = false
      remove server
    }
  }

  java {
    toolchain.languageVersion = JavaLanguageVersion.of 8
    withSourcesJar()
  }

  processResources {
    def stringProperties = project.properties.findAll { it.value instanceof String }
    inputs.properties stringProperties
    filesMatching 'fabric.mod.json', {
      expand stringProperties, { escapeBackslash = false }
    }
  }

  idea.module.resourceDirs = [ project.processResources.destinationDir ]
  idea.module.generatedSourceDirs += project.processResources.destinationDir

  tasks.withType Jar configureEach {
    from rootProject.file('LICENSE')
  }

  test {
    useJUnitPlatform()
    workingDir = rootProject.layout.buildDirectory.file 'test-run'
    workingDir.mkdir()
  }

  if (project != rootProject)
    rootProject.dependencies {
      include project
    }
}

base.archivesName = mod_id
