# Gradle Properties
org.gradle.caching = true
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Mod Properties
maven_group = io.github.crazysmc
mod_id = thorough-keybindings
mod_version = 3.2.0+fabric-unobf

minecraft_range = >=26.1-alpha.1
java_version = 25
minecraft_version = 26.1
fabric_api_version = 0.145.1+26.1
