pluginManagement {
  repositories {
    maven {
      name = 'Fabric'
      url = 'https://maven.fabricmc.net/'
    }
    gradlePluginPortal()
  }
}

dependencyResolutionManagement {
  versionCatalogs {
    libs {
      version 'loom', '1.16-SNAPSHOT'
      plugin 'loom', 'net.fabricmc.fabric-loom' versionRef 'loom'
      version 'loader', '0.19.3'
      library 'loader', 'net.fabricmc', 'fabric-loader' versionRef 'loader'
      library 'junit', 'org.junit.jupiter', 'junit-jupiter' version '5.10.2'
      library 'loader-junit', 'net.fabricmc', 'fabric-loader-junit' versionRef 'loader'
      library 'mockito', 'org.mockito', 'mockito-junit-jupiter' version '3.+'
    }
  }
}

rootProject.name = 'thrkbs'
