pluginManagement {
  repositories {
    maven {
      name = 'Fabric'
      url = 'https://maven.fabricmc.net/'
    }
    gradlePluginPortal()
  }
}

dependencyResolutionManagement {
  versionCatalogs {
    libs {
      version 'loom', '1.11-SNAPSHOT'
      plugin 'loom', 'fabric-loom' versionRef 'loom'
      version 'loader', '0.17.2'
      library 'loader', 'net.fabricmc', 'fabric-loader' versionRef 'loader'
      library 'junit', 'org.junit.jupiter', 'junit-jupiter' version '5.10.2'
      library 'loader-junit', 'net.fabricmc', 'fabric-loader-junit' versionRef 'loader'
      library 'mockito', 'org.mockito', 'mockito-junit-jupiter' version '3.+'
      library 'mojang-logging', 'com.mojang', 'logging' version '1.0.0' // work around FabricMC/fabric-loader#817
    }
  }
}

rootProject.name = 'thrkbs'

include ':version:1.14'
include ':version:20w10a'
include ':version:20w17a'
include ':version:1.16'
include ':version:1.17'
include ':version:1.19'
//include ':version:1.21.9'
