minecraft_range = >=1.20.3-alpha.23.40.a <1.21.2-beta.1
java_version = 17
minecraft_version = 1.20.3
fabric_api_version = 0.91.1+1.20.3

#java_version = 21
#minecraft_version = 1.20.5
#fabric_api_version = 0.97.8+1.20.5

#java_version = 21
#minecraft_version = 1.21
#fabric_api_version = 0.102.0+1.21

# 23w40a adds Component.translatableEscape
