minecraft_range = >=1.17-alpha.21.20.a <1.19-alpha.22.16.a
java_version = 16
minecraft_version = 1.17.1
fabric_api_version = 0.46.1+1.17

#minecraft_version = 21w20a

#minecraft_version = 1.17

#java_version = 17
#minecraft_version = 1.18
#fabric_api_version = 0.44.0+1.18

#java_version = 17
#minecraft_version = 22w15a
#fabric_api_version = 0.58.0+1.19
#no_fabric_resource_loader = 1

# 21w20a changes ContainerEventHandler to Screen
