sourceSets.main {
  java {
    srcDirs += file '../src/1.13-1.14/java/'

    include '**/mixin/shared/ControlsOptionsScreenMixinGLFW.java'
    include '**/mixin/shared/DebugOverlayMixin.java'
    include '**/mixin/shared/KeyBindingMixinGLFW.java'
    include '**/mixin/shared/KeyboardHandlerMixin.java'
    include '**/shared/RemappedTranslatableText.java'
  }
  resources.srcDirs += file '../src/1.13-1.14/resources/'
}
