sourceSets.main.java {
  include '**/mixin/shared/ControlsScreenMixin.java'
  include '**/mixin/shared/DebugScreenOverlayMixin.java'
  include '**/mixin/shared/KeyboardHandlerMixin.java'
  include '**/mixin/shared/KeyboardHandlerMixinControls.java'
  include '**/mixin/shared/KeyMappingAccessor.java'
  include '**/mixin/shared/KeyMappingMixin.java'
  include '**/mixin/shared/ScreenMixin.java'
}
