sourceSets.main.java {
  srcDirs += file '../1.21.9/src/main/java'
  exclude {
    it.file in [
        file('../1.21.9/src/main/java/io/github/crazysmc/thrkbs/version/Categories.java'),
        file('../1.21.9/src/main/java/io/github/crazysmc/thrkbs/version/KeyRemapping.java'),
    ]
  }
}
apply from: '../1.21.9/build.gradle'
