sourceSets.main.java {
  srcDirs += file '../src/1.16-1.21/java'

  include '**/mixin/shared/AbstractContainerScreenMixin.java'
  include '**/mixin/shared/KeyBindsScreenMixinOpt.java'
  include '**/mixin/shared/DebugScreenOverlayMixinEdit.java'
  include '**/mixin/shared/GameModeSwitcherScreenMixin.java'
  include '**/mixin/shared/KeyboardHandlerMixin.java'
  include '**/mixin/shared/KeyboardHandlerMixinComponent.java'
  include '**/mixin/shared/KeyboardHandlerMixinKeyBindsOpt.java'
  include '**/mixin/shared/KeyMappingAccessor.java'
  include '**/mixin/shared/KeyMappingMixin.java'
  include '**/mixin/shared/MinecraftMixin.java'
  include '**/mixin/shared/RecipeBookComponentMixin.java'
  include '**/shared/RemappedTranslatableContents.java'
}
